### ISSUE TITLE
BatchNorm2d support

### ISSUE THREAD

**Issue by mzweilin** [KaidiXu/auto_LiRPA#1]
Hi there,

I added a BatchNorm2d layer in the model and auto-LiRPA failed to parse the graph. Is it a bug?

```console
$ python simple_training.py --num_epochs 3 --scheduler_opts "start=2,length=1"
Traceback (most recent call last):
  File "simple_training.py", line 203, in <module>
    main(args)
  File "simple_training.py", line 170, in main
    model = BoundedModule(model_ori, dummy_input, args.bound_opts, device=args.device)
  File "/home/weilinxu/Envs/autoLiRPA/lib/python3.6/site-packages/auto_LiRPA-0.1-py3.6.egg/auto_LiRPA/bound_general.py", line 22, in __init__
  File "/home/weilinxu/Envs/autoLiRPA/lib/python3.6/site-packages/auto_LiRPA-0.1-py3.6.egg/auto_LiRPA/bound_general.py", line 230, in _convert
  File "/home/weilinxu/Envs/autoLiRPA/lib/python3.6/site-packages/auto_LiRPA-0.1-py3.6.egg/auto_LiRPA/bound_general.py", line 119, in _convert_nodes
  File "/home/weilinxu/Envs/autoLiRPA/lib/python3.6/site-packages/auto_LiRPA-0.1-py3.6.egg/auto_LiRPA/parse_graph.py", line 135, in get_graph_params
  File "/home/weilinxu/Envs/autoLiRPA/lib/python3.6/site-packages/auto_LiRPA-0.1-py3.6.egg/auto_LiRPA/parse_graph.py", line 65, in parse
AssertionError
```

**Comment by huanzhang12** [comment]
@mzweilin We have an internal development version that does provide initial BatchNorm2d support. We will release it within a few weeks. Could you please share your network structure definition (in Pytorch) with us so we can test it? Thanks.

**Comment by mzweilin** [comment]
Thanks for the update, Huan. I'm looking to that release!

I just inserted BN between Conv layers in the cnn_4layer model.

BTW, are you going to add support to other normalization methods, such as group normalization?

**Comment by huanzhang12** [comment]
@mzweilin Thanks for providing this information! We will certainly test the cnn_4layer model with BNs.

We are also working on group normalization, stay tuned! :slightly_smiling_face:

**Comment by Kozon2015** [comment]
**Hi !
I use 'simple_verification.py' to test my pretrained model(a model trained by resnet18), and auto-LiRPA failed to parse the graph. Is it a bug?**

```
len of params: 108
len of list(graph.inputs()): 129
Traceback (most recent call last):
  File "simple_verification.py", line 74, in <module>
    model = BoundedModule(model, torch.empty_like(image), device="cuda")
  File "/home/kzw/verify_robustness/auto_LiRPA/bound_general.py", line 22, in __init__
    self._convert(model, global_input)
  File "/home/kzw/verify_robustness/auto_LiRPA/bound_general.py", line 230, in _convert
    nodesOP, nodesIO = self._convert_nodes(model, global_input)
  File "/home/kzw/verify_robustness/auto_LiRPA/bound_general.py", line 119, in _convert_nodes
    nodesOP, nodesIO = get_graph_params(model, global_input_cpu)
  File "/home/kzw/verify_robustness/auto_LiRPA/parse_graph.py", line 142, in get_graph_params
    nodesOP, nodesIO = parse(torch_graph, params)
  File "/home/kzw/verify_robustness/auto_LiRPA/parse_graph.py", line 67, in parse
    assert len(list(graph.inputs())) == len(params)
AssertionError
```


**These are parts of 'torch_graph' as follow, I found the number of  ‘Long()’ is the number that length of 'torch_graph' is more than length of params.**

```
graph(%0 : Float(1, 3, 32, 32)
      %1 : Float(64, 3, 3, 3)
      %2 : Float(64)
      %3 : Float(64)
      %4 : Float(64)
      %5 : Float(64)
      %6 : Long()
      %7 : Float(64, 64, 3, 3)
      %8 : Float(64)
      %9 : Float(64)
      %10 : Float(64)
      %11 : Float(64)
      %12 : Long()
      %13 : Float(64, 64, 3, 3)
      %14 : Float(64)
      %15 : Float(64)
      %16 : Float(64)
      %17 : Float(64)
      %18 : Long()
      %19 : Float(64, 64, 3, 3)
      %20 : Float(64)
      %21 : Float(64)
      %22 : Float(64)
      %23 : Float(64)
      %24 : Long()
```

**Comment by huanzhang12** [comment]
@Kozon2015 Thank you for the detailed report! Yes the `Long()` variables can indeed be a problem. Could you please share us with your code?
BTW, we are preparing for a new release of the library, which contains many bug fixes. If you can provide us your code, we will look into this issue in detail can make sure that it can be correctly parsed in our new release. Thanks!

**Comment by shizhouxing** [comment]
@Kozon2015 Currently an issue as the one you showed can appear if there is any unused input (arguments of the `forward` function of the module that are not actually used). I'm not sure if this is the case for you?

**Comment by Kozon2015** [comment]
> @Kozon2015 Thank you for the detailed report! Yes the `Long()` variables can indeed be a problem. Could you please share us with your code?
> BTW, we are preparing for a new release of the library, which contains many bug fixes. If you can provide us your code, we will look into this issue in detail can make sure that it can be correctly parsed in our new release. Thanks!

Hi! I ran 'simple_verification.py' in auto_LiRPA to get the bounds of a pretrained resnet18 provided in torchvision  and got the `Long()` error described above. I have also trained a network using 'example_resnet.py' on CIFAR100. But when running 'simple_verification.py' on the CIFAR100 model, I got the following error: 

`‘RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 31.72 GiB total capacity; 28.16 GiB already allocated; 989.56 MiB free; 1.45 GiB cached)’ My GPU is 32G.`

**Comment by Harry24k** [comment]
Hi, i have same problems as above under torch=1.4.0.

`import torchvision.models as models
from auto_LiRPA import BoundedModule, BoundedTensor, PerturbationLpNorm
import numpy as np

model = models.resnet18()
my_input = torch.randn((1, 3, 224, 224))

# Wrap the model with auto_LiRPA
bmodel = BoundedModule(model, my_input)
# Define perturbation
ptb = PerturbationLpNorm(norm=np.inf, eps=8/255)
# Make the input a BoundedTensor with perturbation
my_input = BoundedTensor(my_input, ptb)
# Forward propagation using BoundedTensor
prediction = bmodel(my_input)
# Compute LiRPA bounds
lb, ub = bmodel.compute_bounds(method="backward")`

The results are as follows :

`params = _get_jit_params(model, param_exclude=".*AuxLogits.*", param_include=None)
for i, j in enumerate(list(params)) :
    print("#", i,":", j[0])`

`# 0 : conv1.weight
# 1 : bn1.weight
# 2 : bn1.bias
# 3 : bn1.running_mean
# 4 : bn1.running_var
# 5 : layer1.0.conv1.weight
# 6 : layer1.0.bn1.weight
# 7 : layer1.0.bn1.bias
# 8 : layer1.0.bn1.running_mean
# 9 : layer1.0.bn1.running_var
# 10 : layer1.0.conv2.weight
# 11 : layer1.0.bn2.weight
# 12 : layer1.0.bn2.bias
# 13 : layer1.0.bn2.running_mean
# 14 : layer1.0.bn2.running_var
# 15 : layer1.1.conv1.weight
# 16 : layer1.1.bn1.weight
# 17 : layer1.1.bn1.bias
# 18 : layer1.1.bn1.running_mean
# 19 : layer1.1.bn1.running_var
# 20 : layer1.1.conv2.weight
# 21 : layer1.1.bn2.weight
# 22 : layer1.1.bn2.bias
# 23 : layer1.1.bn2.running_mean
# 24 : layer1.1.bn2.running_var
# 25 : layer2.0.conv1.weight
# 26 : layer2.0.bn1.weight
# 27 : layer2.0.bn1.bias
# 28 : layer2.0.bn1.running_mean
# 29 : layer2.0.bn1.running_var
# 30 : layer2.0.conv2.weight
# 31 : layer2.0.bn2.weight
# 32 : layer2.0.bn2.bias
# 33 : layer2.0.bn2.running_mean
# 34 : layer2.0.bn2.running_var
# 35 : layer2.0.downsample.0.weight
# 36 : layer2.0.downsample.1.weight
# 37 : layer2.0.downsample.1.bias
# 38 : layer2.0.downsample.1.running_mean
# 39 : layer2.0.downsample.1.running_var
# 40 : layer2.1.conv1.weight
# 41 : layer2.1.bn1.weight
# 42 : layer2.1.bn1.bias
# 43 : layer2.1.bn1.running_mean
# 44 : layer2.1.bn1.running_var
# 45 : layer2.1.conv2.weight
# 46 : layer2.1.bn2.weight
# 47 : layer2.1.bn2.bias
# 48 : layer2.1.bn2.running_mean
# 49 : layer2.1.bn2.running_var
# 50 : layer3.0.conv1.weight
# 51 : layer3.0.bn1.weight
# 52 : layer3.0.bn1.bias
# 53 : layer3.0.bn1.running_mean
# 54 : layer3.0.bn1.running_var
# 55 : layer3.0.conv2.weight
# 56 : layer3.0.bn2.weight
# 57 : layer3.0.bn2.bias
# 58 : layer3.0.bn2.running_mean
# 59 : layer3.0.bn2.running_var
# 60 : layer3.0.downsample.0.weight
# 61 : layer3.0.downsample.1.weight
# 62 : layer3.0.downsample.1.bias
# 63 : layer3.0.downsample.1.running_mean
# 64 : layer3.0.downsample.1.running_var
# 65 : layer3.1.conv1.weight
# 66 : layer3.1.bn1.weight
# 67 : layer3.1.bn1.bias
# 68 : layer3.1.bn1.running_mean
# 69 : layer3.1.bn1.running_var
# 70 : layer3.1.conv2.weight
# 71 : layer3.1.bn2.weight
# 72 : layer3.1.bn2.bias
# 73 : layer3.1.bn2.running_mean
# 74 : layer3.1.bn2.running_var
# 75 : layer4.0.conv1.weight
# 76 : layer4.0.bn1.weight
# 77 : layer4.0.bn1.bias
# 78 : layer4.0.bn1.running_mean
# 79 : layer4.0.bn1.running_var
# 80 : layer4.0.conv2.weight
# 81 : layer4.0.bn2.weight
# 82 : layer4.0.bn2.bias
# 83 : layer4.0.bn2.running_mean
# 84 : layer4.0.bn2.running_var
# 85 : layer4.0.downsample.0.weight
# 86 : layer4.0.downsample.1.weight
# 87 : layer4.0.downsample.1.bias
# 88 : layer4.0.downsample.1.running_mean
# 89 : layer4.0.downsample.1.running_var
# 90 : layer4.1.conv1.weight
# 91 : layer4.1.bn1.weight
# 92 : layer4.1.bn1.bias
# 93 : layer4.1.bn1.running_mean
# 94 : layer4.1.bn1.running_var
# 95 : layer4.1.conv2.weight
# 96 : layer4.1.bn2.weight
# 97 : layer4.1.bn2.bias
# 98 : layer4.1.bn2.running_mean
# 99 : layer4.1.bn2.running_var
# 100 : fc.weight
# 101 : fc.bias`

`trace, out = torch.jit._get_trace_graph(model, my_input)
torch_graph = torch.onnx._optimize_trace(trace, torch.onnx.OperatorExportTypes.ONNX)
for i, j in enumerate(list(torch_graph.inputs())) :
    print("#", i,":", j)`

`%input.1 : Float(1, 3, 224, 224), %1 : Float(64, 3, 7, 7), %2 : Float(64), %3 : Float(64), %4 : Float(64), %5 : Float(64), %6 : Long(), %7 : Float(64, 64, 3, 3), %8 : Float(64), %9 : Float(64), %10 : Float(64), %11 : Float(64), %12 : Long(), %13 : Float(64, 64, 3, 3), %14 : Float(64), %15 : Float(64), %16 : Float(64), %17 : Float(64), %18 : Long(), %19 : Float(64, 64, 3, 3), %20 : Float(64), %21 : Float(64), %22 : Float(64), %23 : Float(64), %24 : Long(), %25 : Float(64, 64, 3, 3), %26 : Float(64), %27 : Float(64), %28 : Float(64), %29 : Float(64), %30 : Long(), %31 : Float(128, 64, 3, 3), %32 : Float(128), %33 : Float(128), %34 : Float(128), %35 : Float(128), %36 : Long(), %37 : Float(128, 128, 3, 3), %38 : Float(128), %39 : Float(128), %40 : Float(128), %41 : Float(128), %42 : Long(), %43 : Float(128, 64, 1, 1), %44 : Float(128), %45 : Float(128), %46 : Float(128), %47 : Float(128), %48 : Long(), %49 : Float(128, 128, 3, 3), %50 : Float(128), %51 : Float(128), %52 : Float(128), %53 : Float(128), %54 : Long(), %55 : Float(128, 128, 3, 3), %56 : Float(128), %57 : Float(128), %58 : Float(128), %59 : Float(128), %60 : Long(), %61 : Float(256, 128, 3, 3), %62 : Float(256), %63 : Float(256), %64 : Float(256), %65 : Float(256), %66 : Long(), %67 : Float(256, 256, 3, 3), %68 : Float(256), %69 : Float(256), %70 : Float(256), %71 : Float(256), %72 : Long(), %73 : Float(256, 128, 1, 1), %74 : Float(256), %75 : Float(256), %76 : Float(256), %77 : Float(256), %78 : Long(), %79 : Float(256, 256, 3, 3), %80 : Float(256), %81 : Float(256), %82 : Float(256), %83 : Float(256), %84 : Long(), %85 : Float(256, 256, 3, 3), %86 : Float(256), %87 : Float(256), %88 : Float(256), %89 : Float(256), %90 : Long(), %91 : Float(512, 256, 3, 3), %92 : Float(512), %93 : Float(512), %94 : Float(512), %95 : Float(512), %96 : Long(), %97 : Float(512, 512, 3, 3), %98 : Float(512), %99 : Float(512), %100 : Float(512), %101 : Float(512), %102 : Long(), %103 : Float(512, 256, 1, 1), %104 : Float(512), %105 : Float(512), %106 : Float(512), %107 : Float(512), %108 : Long(), %109 : Float(512, 512, 3, 3), %110 : Float(512), %111 : Float(512), %112 : Float(512), %113 : Float(512), %114 : Long(), %115 : Float(512, 512, 3, 3), %116 : Float(512), %117 : Float(512), %118 : Float(512), %119 : Float(512), %120 : Long(), %121 : Float(1000, 512), %122 : Float(1000) = prim::Param()`

**Comment by huanzhang12** [comment]
@Kozon2015 If your CIFAR-100 network was trained using `simple_training.py`, you should use IBP or CROWN-IBP to verify it.
`simple_verification.py` defaulting to the more expansive CROWN bounds, which takes significantly more memory.
Basically, you nee to change this line: https://github.com/KaidiXu/auto_LiRPA/blob/d939ace6e3332659da06e8b02ae0c2ff3c4f62fe/examples/vision/simple_verification.py#L52
to:
```
lb, ub = model.compute_bounds(IBP=True, method=None)
```
to use IBP bounds instead of CROWN bounds.

**Comment by huanzhang12** [comment]
@Harry24k Thank you for the detailed report! We will look into this. We plan to release a new version of `auto_LiRPA` soon which will try to fix this problem.

**Comment by Harry24k** [comment]
> @Harry24k Thank you for the detailed report! We will look into this. We plan to release a new version of `auto_LiRPA` soon which will try to fix this problem.

Thanks! I'm looking forward to it.

**Comment by Harry24k** [comment]
I don't know if this will help, I temporarily fixed it like [this](https://github.com/Harry24k/auto_LiRPA/commit/c063ced83a50beabfe1c1a8ad47f895753c33625). However, due to Maxpool2d of ResNet, it still prints an error.

**Comment by mzweilin** [comment]
> @mzweilin We have an internal development version that does provide initial BatchNorm2d support. We will release it within a few weeks. Could you please share your network structure definition (in Pytorch) with us so we can test it? Thanks.

Hi @huanzhang12 , just want to follow up. Is there a revised plan to release the feature?

**Comment by huanzhang12** [comment]
@mzweilin We will make a new release later today.

**Comment by huanzhang12** [comment]
@mzweilin @Harry24k @Kozon2015 We release a new version of `auto_LiRPA` today, which comes with batchnorm support.
An example of `resnet18` with batchnorm can be found here: https://github.com/KaidiXu/CROWN-GENERAL/blob/master/examples/vision/models/resnet18.py
You can use `cifar_training.py` to train this model:
```
python cifar_training.py --model resnet18
```
It takes about 80 seconds to train 1 epoch on 4x 1080 Ti GPUs using CROWN-IBP plus loss fusion.
