### ISSUE TITLE
Using DataParallel Wrapped Models

### ISSUE THREAD

**Issue by hx507** [KaidiXu/auto_LiRPA#14]
Is it possible to calculate bounds for models inside torch's `DataParallel` wrapper? 

I see `BoundedDataParallel` is implemented, but creating a `BoundedModule` will force a cpu tensor be passed through the model (`bounded_general.py:401`), which does not work for Data-parallel wrapped models. Is there any possible way to make that work?

**Comment by huanzhang12** [comment]
We do have support for multiGPU parallelization. You will need the `BoundDataParallel` object. You can checkout the `cifar_training.py` example:

https://github.com/KaidiXu/auto_LiRPA/blob/10a9b30f423b56481bbc055dd8d53968a3e7d1ab/examples/vision/cifar_training.py#L260-L263

And for computing bounds you need to call the model with `method_opt="compute_bound"`:

https://github.com/KaidiXu/auto_LiRPA/blob/10a9b30f423b56481bbc055dd8d53968a3e7d1ab/examples/vision/cifar_training.py#L82-L84

For training there are some additional tricks like `CrossEntropyWrapper` but if you just need to compute bounds you should be able to simplify the code above.
