### ISSUE TITLE
Warning For a resnet with 2 resnet blocks

### ISSUE THREAD

**Issue by Sawinder-Kaur** [KaidiXu/auto_LiRPA#15]
Hi,
I was trying to generate bounds for SVHN dataset on a small Resnet with 2 resnet blocks and got this warning: "UserWarning: Creating an identity matrix with size 1024x1024 for node BoundConv(). This may indicate poor performance for bound computation. If you see this message on a small network please submit a bug report."

**Comment by huanzhang12** [comment]
Thank you for reporting the problem to us!
Could you post your network architecture here? We can take a look and see what is the potential issue. Thanks!

**Comment by Sawinder-Kaur** [comment]
This is the network architecture
ResNet5(
  (conv1): Conv2d(3, 8, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(8, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (shortcut): Sequential(
        (0): Conv2d(8, 16, kernel_size=(1, 1), stride=(2, 2))
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (shortcut): Sequential()
    )
  )
  (linear1): Linear(in_features=1024, out_features=100, bias=True)
  (linear2): Linear(in_features=100, out_features=10, bias=True)
)

**Comment by huanzhang12** [comment]
Thank you for providing this information. Do you have activation functions between the layers (the above printout does not show it)? I recall there are some caveats when defining a model for most efficient bound computation (without this warning). It will be very helpful if you can post your model definition in PyTorch so I can test it.

**Comment by Sawinder-Kaur** [comment]
Hi, Please find attached the file for model definition
[resnet_small.py.zip](https://github.com/KaidiXu/auto_LiRPA/files/7510051/resnet_small.py.zip)

**Comment by shizhouxing** [comment]
Hi @Sawinder-Kaur , I've run your models with `simple_verification.py` but I don't see the warning ([code_and_logs.zip](https://github.com/KaidiXu/auto_LiRPA/files/7516300/issue15.zip)). Are you using the latest version of auto_LiRPA? And how do you run the verification?

**Comment by Sawinder-Kaur** [comment]
Hey, I didn't notice that you updated the code 4 days ago, I was using the July 2021 version. I just tried with the new version and it worked. Thanks for pointing out!

**Comment by shizhouxing** [comment]
@Sawinder-Kaur Great, thanks for your confirmation!
