### ISSUE TITLE
Two bound_forward functions for convolution

### ISSUE THREAD

**Issue by BoyuanFeng** [KaidiXu/auto_LiRPA#17]
Hi authors,

There are two bound_forward functions in the BoundConv class:

1. https://github.com/KaidiXu/auto_LiRPA/blob/master/auto_LiRPA/operators/convolution.py#L155
2. https://github.com/KaidiXu/auto_LiRPA/blob/master/auto_LiRPA/operators/convolution.py#L257

These two functions have the same function names and parameter lists.

I have two questions:
1. It seems that the bound_forward at Line 155 matches with paper description (e.g., need to consider weight>0 and weight<0 when multiplying lb or ub). However, this function shows shape error when the number of input channels of weights is not 1. 
It seems that the issue comes from Line 164~169, which expands weight into a matrix. Can we instead expand images following im2col algorithm?
2. Why do we need the bound_forward function at Line 257?

Thanks!

**Comment by shizhouxing** [comment]
Hi @BoyuanFeng ,

It seems to be an issue of some merging during our development and somehow two different versions show up in the same time. The second version seems to be better as it doesn't require expanding the convolution or creating a large identity matrix.

Currently it seems the second version is actually used when there are two functions. I'll remove the first version. In the second version, while weight>0 or weight <0 is not explicitly considered, it computes a center using the whole weight and a deviation using |weight|, and result should be equivalent. The second version also matches the implementation for IBP bounds.

 In my own test, it works when the number input channels is larger than 1. Does the second version work in your case?

**Comment by BoyuanFeng** [comment]
Thanks a lot for the quick reply!

1. The second version can support the case that the input channels are larger than 1. The first version does not support that.

2. Could you please clarify a bit why the second version and the first version are mathematically equivalent? I can understand that the second version provides certain bounds. However, I am wondering if this bound is not as tight as the first version which explicitly considers weight>0 and weight<0.

3. Just in case that these two versions are not mathematically equivalent. I have a code snippet (attached below) for the first version by expanding images and explicitly considering weight>0 and weight<0. Does this look good to you?

Thanks!

```
def bound_forward(self, dim_in, *x):
        if self.is_input_perturbed(1):
            raise NotImplementedError("Weight perturbation for convolution layers has not been implmented.")
        # lb shape: [batch_size, c_in, h, w]
        # lw shape: [batch_size, dim_in, c_in, h, w]
        # weight shape: [c_out, c_in, k, k]

        weight = x[1].lb
        image = x[0]

        # Expand x_lb, x_ub
        batch_size, cin, h, w = image.lb.shape
        cout, _, k, _ = weight.shape
        expanded_image_lb = torch.nn.functional.pad(image.lb, (self.padding[0], self.padding[0], self.padding[1], self.padding[1])).unfold(2, k, self.stride[0]).unfold(3, k, self.stride[1]).contiguous().view(batch_size, -1, cin*k*k)
        expanded_image_ub = torch.nn.functional.pad(image.ub, (self.padding[0], self.padding[0], self.padding[1], self.padding[1])).unfold(2, k, self.stride[0]).unfold(3, k, self.stride[1]).contiguous().view(batch_size, -1, cin*k*k)

        # Expand weight
        weight = weight.view(cout, cin*k*k).t()

        # Bound computation
        pos_mask = torch.gt(weight, 0).to(torch.float32)
        W_pos = weight * pos_mask
        W_neg = weight - W_pos

        lb = expanded_image_lb.matmul(W_pos) + expanded_image_ub.matmul(W_neg)
        ub = expanded_image_lb.matmul(W_neg) + expanded_image_ub.matmul(W_pos)

        del expanded_image_lb, expanded_image_ub

        expanded_image_lw = torch.nn.functional.pad(image.lw, (self.padding[0], self.padding[0], self.padding[1], self.padding[1])).unfold(3, k, self.stride[0]).unfold(4, k, self.stride[1]).contiguous().view(batch_size, -1, cin*k*k)
        expanded_image_uw = torch.nn.functional.pad(image.uw, (self.padding[0], self.padding[0], self.padding[1], self.padding[1])).unfold(3, k, self.stride[0]).unfold(4, k, self.stride[1]).contiguous().view(batch_size, -1, cin*k*k)

        lw = expanded_image_lw.matmul(W_pos) + expanded_image_uw.matmul(W_neg)
        uw = expanded_image_lw.matmul(W_neg) + expanded_image_uw.matmul(W_pos)

        lw = lw.view(batch_size, dim_in, *self.output_shape[1:])
        uw = uw.view(batch_size, dim_in, *self.output_shape[1:])
        lb = lb.view(batch_size, *self.output_shape[1:])
        ub = ub.view(batch_size, *self.output_shape[1:])
        
        del expanded_image_lw, pos_mask, W_pos, W_neg, weight, image, # expanded_image_uw

        return LinearBound(lw, lb, uw, ub)
```










> Hi @BoyuanFeng ,
> 
> It seems to be an issue of some merging during our development and somehow two different versions show up in the same time. Thanks for raising this issue.
> 
> Currently it seems the second version is actually used when there are two functions. The second version seems to be better as it doesn't require expanding the convolution or creating a large identity matrix. I'll remove the first version. In the second version, while weight>0 or weight <0 is not explicitly considered, it computes a center using the whole weight and a deviation using |weight|, and result should be equivalent. The second version also matches the implementation for IBP bounds.
> 
> In my own test, it works when the number input channels is larger than 1. Does the second version work in your case?

**Comment by shizhouxing** [comment]
Suppose l=lower bound of input, u=upper bound of input, then in the second version, 

output's lower bound 
= W * (l+u)/2 - |W| * (u-l)/2 
= W_positive * ( (l+u)/2 - (u-l)/2 ) + W_negative * ( (l+u)/2 + (u-l)/2 ) 
= W_positive * l + W_negative * u

("*" here can be matrix multiplication for linear layers or convolution)

And this is equivalent to the first version. Computation for the output's upper bound is similar. 

I think it's also ok to do the first version but expanding the convolution may be kind of inefficient. I think another way is to just do convolution using positive weights and negative weights respectively, and then sum up, without expanding the convolution into matmul.

**Comment by BoyuanFeng** [comment]
These two versions are indeed equivalent. Thanks for the clarification!
