### ISSUE TITLE
Dual of LP

### ISSUE THREAD

**Issue by nurlanov-zh** [KaidiXu/auto_LiRPA#19]
Hi, thanks for the nice repo!

Are dual of LP methods included in the library? (Such as https://arxiv.org/abs/1805.12514 )
If not, do you think the current interface is suitable for such approaches?

**Comment by huanzhang12** [comment]
@nurlanov-zh Thanks for the question! The CROWN algorithm implemented in this library is largely equivalent to the dual LP formulation, with some minor differences (i.e., the lower bound slope of ReLU relaxation). This paper https://arxiv.org/pdf/1902.08722 discussed the connection of many formulations. In this paper: https://arxiv.org/pdf/2103.06624.pdf Theorem 3.2 formally proves the equivalence, in a more general setting with split constraints.

In short, CROWN with heuristically set relu lower bound slope (use the same slope as the upper bound) is equivalent to the dual LP with heuristically set alpha variables in http://proceedings.mlr.press/v80/wong18a/wong18a.pdf; CROWN with optimized ReLU lower bound slope (also referred to as alpha-CROWN) is equivalent to dual LP with optimized dual variable. Beta-CROWN is equivalent to dual LP formulation with split constraints.

Let me know if anything is still unclear, thanks!
