### ISSUE TITLE
Performing complete verification

### ISSUE THREAD

**Issue by shubhamugare** [KaidiXu/auto_LiRPA#20]
Hello,

I could find examples to find the bounds using a particular convex relaxation in `simple_verification.py`. 
But is it possible to perform the branch and bound type complete verification using those relaxations?

**Comment by huanzhang12** [comment]
Hi @shubhamugare, thanks for reaching out to us!
You should use the α,β-CROWN (alpha-beta-CROWN) verifier for complete verification with branch and bound: https://github.com/huanzhang12/alpha-beta-CROWN
α,β-CROWN uses the auto_LiRPA library internally for convex relaxation of neural networks.
Let us know if you have any additional questions. Thanks!
