### ISSUE TITLE
Missing normalization of eps?

### ISSUE THREAD

**Issue by ifrosio** [KaidiXu/auto_LiRPA#25]
I may be missing something - when computing the upper / lower bounds for the data in lines 125-128 in cifar_training.py, I see that eps is normalized (i.e. it is divided by loader.std):

            data_max = torch.reshape((1. - loader.mean) / loader.std, (1, -1, 1, 1))
            data_min = torch.reshape((0. - loader.mean) / loader.std, (1, -1, 1, 1))
            data_ub = torch.min(data + (eps / loader.std).view(1,-1,1,1), data_max)
            data_lb = torch.max(data - (eps / loader.std).view(1,-1,1,1), data_min)

At line 136, when the perturbation is created, this division is missing:

            ptb = PerturbationLpNorm(norm=norm, eps=eps, x_L=data_lb, x_U=data_ub)

Is it possible that here, as well as in other example files, the considered eps is indeed too small, as it is not divided by loader.std (~0.2 for cifar)?

Thanks

**Comment by shizhouxing** [comment]
Hi @ifrosio , for `PerturbationLpNorm`, when `x_L` and `x_U` are specified, the perturbation box for input is determined by `x_L` and `x_U`, and in this case `eps` is not really used. eps is already normalized in `x_L` and `x_U`. Sorry for the confusion. Normalizing eps (or `x_L` and `x_U`) is necessary for soundness.

**Comment by huanzhang12** [comment]
@ifrosio PerturbationLpNorm will use `x_L` and `x_U` if they are specified for Linf norm; `eps` is ignored in that case. See: 
https://github.com/KaidiXu/auto_LiRPA/blob/02f6266518715112f840044675095f635c8ec18b/auto_LiRPA/perturbations.py#L162-L165

**Comment by ifrosio** [comment]
Perfectly clear, thanks!
