### ISSUE TITLE
Intermediate bounds

### ISSUE THREAD

**Issue by nurlanov-zh** [KaidiXu/auto_LiRPA#26]
@huanzhang12 However, such obtained bounds will not be the same as in CROWN method, won't they? I wanted to look at intermediate bounds from particular methods. Is it possible to obtain those, even though the efficiency is reduced?

_Originally posted by @nurlanov-zh in https://github.com/KaidiXu/auto_LiRPA/issues/22#issuecomment-1092565059_

**Comment by shizhouxing** [comment]
Hi @nurlanov-zh , now you may call `compute_bounds` to get the bounds for a specific node by specifying `final_node_name`:
```
bounded_model.compute_bounds(method='CROWN', final_node_name=node.name)
```
