### ISSUE TITLE
Batch of epsilon

### ISSUE THREAD

**Issue by nurlanov-zh** [KaidiXu/auto_LiRPA#29]
Hello,

Is it possible to compute bounds for a batch of inputs with different epsilon bounds? I discovered it could be done for L_inf norm, but non-trivial for other norms.

Thanks!

**Comment by shizhouxing** [comment]
Hi @nurlanov-zh , currently in [`PerturbationLpNorm`](https://github.com/KaidiXu/auto_LiRPA/blob/master/auto_LiRPA/perturbations.py#L127), we assume `eps` is a scalar. It sounds like in your case `eps` needs to accept a 1-D tensor. I think this would require some small modification to some lines in [`PerturbationLpNorm`](https://github.com/KaidiXu/auto_LiRPA/blob/master/auto_LiRPA/perturbations.py#L127) involving `eps` to ensure that `eps` is correctly broadcast. I think you may create a new Perturbation class inheriting `PerturbationLpNorm` and slightly modify those related lines.
