### ISSUE TITLE
auto Lirpa on other domains than Lp balls ?

### ISSUE THREAD

**Issue by mducoffe** [KaidiXu/auto_LiRPA#30]
Hi and thank you for this great library !

I was wondering it auto Lirpa could be applied on other domains than Lp balls on minibatches ? For example hyper-rectangles ?

Thank you for your time !

**Comment by shizhouxing** [comment]
Hi @mducoffe ,

Yes, hyper-rectangles are supported and you may still use `PerturbationLpNorm`, by:
```
ptb = PerturbationLpNorm(x_L=x_L, x_U=x_U)
```
where `x_L` and `x_U` are lower and upper bounds for the hyper-rectangle. 

And other perturbations may be added by creating a new [perturbation class](https://auto-lirpa.readthedocs.io/en/latest/api.html#auto_LiRPA.perturbations.Perturbation).
