### ISSUE TITLE
Bound of difference != difference of bound?

### ISSUE THREAD

**Issue by haoming-codes** [KaidiXu/auto_LiRPA#31]
In running the sample code `auto_LiRPA/examples/vision/simple_training.py --bound_type IBP`, I was trying to test whether {the bound of the margin between classes} is equal to {the difference between the bound between classes}. 

Specifically, I did
```
c1 = the specification matrix from the paper
c2 = c1.clone(); c2[c2==-1] = 0
c3 = c1.clone(); c3[c3==1] = 0
lb1, ub1 = model.compute_bounds(IBP=True, C=c1, method=None)
lb2, ub2 = model.compute_bounds(IBP=True, C=c2, method=None)
lb3, ub3 = model.compute_bounds(IBP=True, C=c3, method=None)
```

I expect `lb1 == lb2+lb3` and `ub1 == ub2+ub3`, but they are not equal. Is this expected?

**Comment by haoming-codes** [comment]
Can you please elaborate more? Why should the tightness be different?

**Comment by huanzhang12** [comment]
@haoming-codes lb1 should be tighter than lb2+lb3 and ub1 should be tighter than ub2+ub3, due to the last layer elision trick.
See https://arxiv.org/pdf/1810.12715.pdf

**Comment by haoming-codes** [comment]
@huanzhang12 @shizhouxing Thank you!
