### ISSUE TITLE
upper bound and lower bound are always equal

### ISSUE THREAD

**Issue by QuXinghuaNTU** [KaidiXu/auto_LiRPA#6]
Hi,

Recently I am using your auto_LiRPA to compute the perturbation bound of hidden features. However, I found that the ub and lb are always exactly the same.
```
eps = 0.012
actions = actions.cuda() 
states = states.to(torch.float)/255.0
actions = actions.to(torch.float)
eps_v = eps
state_max = 1.0
state_min = 0.0
state_ub = torch.clamp(states + eps_v, max=state_max)
state_lb = torch.clamp(states - eps_v, min=state_min)
ptb = PerturbationLpNorm(norm = np.inf, eps=eps, x_L=state_lb, x_U=state_ub)
bnd_states = BoundedTensor(states, ptb)
bnd_states = bnd_states.cuda()
#####################################
features = featurenet(bnd_states)
q_values = qnet(features)  # input x and predict based on x
labels = torch.argmax(actions, dim=1)
loss = loss_func(q_values, labels) 
####################################
lb, ub = featurenet.compute_bounds(IBP=False)  
print(torch.mean(lb).item(), torch.mean(ub).item(), torch.max(lb).item(), torch.max(ub).item())
```
The print results show that the ub and lb are always same.
```
0.450094610452652 0.450094610452652 2.707549571990967 2.707549571990967
0.48474934697151184 0.48474934697151184 2.94636869430542 2.94636869430542
0.46419665217399597 0.46419665217399597 2.889254093170166 2.889254093170166
0.481861412525177 0.481861412525177 3.1563448905944824 3.1563448905944824
0.48333269357681274 0.48333269357681274 3.0463905334472656 3.0463905334472656
0.4830339848995209 0.4830339848995209 3.1504933834075928 3.1504933834075928
0.49715957045555115 0.49715957045555115 3.2522659301757812 3.2522659301757812
0.478254109621048 0.478254109621048 3.142927408218384 3.142927408218384
0.5154712200164795 0.5154712200164795 3.2538249492645264 3.2538249492645264
0.49771052598953247 0.49771052598953247 3.1791763305664062 3.1791763305664062
0.4898771643638611 0.4898771643638611 3.212333917617798 3.212333917617798
0.5144965648651123 0.5144965648651123 3.347181558609009 3.347181558609009
```

**Comment by shizhouxing** [comment]
Hi @QuXinghuaNTU , could you please show the value of `states` and model structure/operations involved in your `featurenet`? It seems that the above code should work well at least if `featurenet` is a simple MLP or CNN and the value of `states` looks good.

**Comment by QuXinghuaNTU** [comment]
Hi Zhouxing,

Thanks for the quick response.
The featurenet is quite simple as shown below.
```
class Feature_Net(torch.nn.Module):
    def __init__(self, state_dim):
        super(Feature_Net, self).__init__()
        self.features = nn.Sequential(
                        nn.Conv2d(state_dim[0], 32, kernel_size=8, stride=4),
                        nn.ReLU(),
                        nn.Conv2d(32, 64, kernel_size=4, stride=2),
                        nn.ReLU(),
                        nn.Conv2d(64, 64, kernel_size=3, stride=1),
                        nn.ReLU(),
                        Flatten(),
                        nn.Linear(3136, 512),
                        nn.ReLU())

    def forward(self, states):
        features = self.features(states)                 
        return features
```
The states are collected atari game observations with the size of ``` (4,84,84)```.

**Comment by huanzhang12** [comment]
@QuXinghuaNTU You should switch the two lines:
```
bnd_states = BoundedTensor(states, ptb)
bnd_states = bnd_states.cuda()
```

The correct way is to do this:
```
states = states.cuda()
bnd_states = BoundedTensor(states, ptb)
```

After calling `.cuda()`, the BoundedTensor becomes a normal `torch.Tensor` and the bound property gets lost. @shizhouxing maybe you can take a look on how to avoid this.

BTW @QuXinghuaNTU we have a project on using auto_LiRPA with Atari DQN, which might be helpful for you: https://github.com/chenhongge/SA_DQN You can find most relevant code [here](https://github.com/chenhongge/SA_DQN/blob/147e342660008e3d455625e4bd8a950424e825cd/train.py#L39) and [here](https://github.com/chenhongge/SA_DQN/blob/master/models.py#L56)

**Comment by shizhouxing** [comment]
Thanks @huanzhang12 ! Currently it seems that the following usage also works:

```
bnd_states = BoundedTensor(states, ptb)
bnd_states = bnd_states.to('cuda')
```

To make `.cuda()` work, I think we can handle it in `__torch_function__`: https://github.com/KaidiXu/CROWN-GENERAL/blob/master/auto_LiRPA/bounded_tensor.py#L63 (check if `func` is `.cuda()` and handle it similarly as https://github.com/KaidiXu/CROWN-GENERAL/blob/master/auto_LiRPA/bounded_tensor.py#L40).

**Comment by QuXinghuaNTU** [comment]
> Thanks @huanzhang12 ! Currently it seems that the following usage also works:
> 
> ```
> bnd_states = BoundedTensor(states, ptb)
> bnd_states = bnd_states.to('cuda')
> ```
> 
> To make `.cuda()` work, I think we can handle it in `__torch_function__`: https://github.com/KaidiXu/CROWN-GENERAL/blob/master/auto_LiRPA/bounded_tensor.py#L63 (check if `func` is `.cuda()` and handle it similarly as https://github.com/KaidiXu/CROWN-GENERAL/blob/master/auto_LiRPA/bounded_tensor.py#L40).

@shizhouxing Yes, as pointed out, both ways work fine. The issue is caused by `state_lb ` and `state_ub ` are not passed to `cuda`. For some reason, the code does not check the match of data types. After fixing this, I found the gpu memory increases significantly after using `BoundedTensor`. 
The memory using plain training (without using BoundedTensor to get `bnd_states `) is:
![image](https://user-images.githubusercontent.com/36146785/103959496-c9541680-518a-11eb-89a0-69daf4df6bfb.png)
While the memory usage after using `BoundedTensor ` changed to be:
![image](https://user-images.githubusercontent.com/36146785/103959540-e2f55e00-518a-11eb-9f3b-986301a5e84c.png)
Moreover, this is from the `batch size` with `4`. Setting a larger value of `batch size`  causes `out of memory` issue.

**Comment by QuXinghuaNTU** [comment]
> @QuXinghuaNTU You should switch the two lines:
> 
> ```
> bnd_states = BoundedTensor(states, ptb)
> bnd_states = bnd_states.cuda()
> ```
> 
> The correct way is to do this:
> 
> ```
> states = states.cuda()
> bnd_states = BoundedTensor(states, ptb)
> ```
> 
> After calling `.cuda()`, the BoundedTensor becomes a normal `torch.Tensor` and the bound property gets lost. @shizhouxing maybe you can take a look on how to avoid this.
> 
> BTW @QuXinghuaNTU we have a project on using auto_LiRPA with Atari DQN, which might be helpful for you: https://github.com/chenhongge/SA_DQN You can find most relevant code [here](https://github.com/chenhongge/SA_DQN/blob/147e342660008e3d455625e4bd8a950424e825cd/train.py#L39) and [here](https://github.com/chenhongge/SA_DQN/blob/master/models.py#L56)

Many thanks for the reply, @huanzhang12 :)
Also thanks for introducing your NeurIPS paper. Actually, I did read that one https://github.com/chenhongge/SA_DQN when March 2020. One of my previous works on Adversary [Agnostic Robust Deep Reinforcement Learning](https://arxiv.org/pdf/2008.06199.pdf) is inspired by the SA-MDP.

**Comment by huanzhang12** [comment]
@QuXinghuaNTU  Nice work! I am glad to know that my paper was inspiring. Feel free to let me know if you have any additional questions on my paper.

To reduce memory usage, you can turn on the "patches" mode for convolution. This can be very useful if you have set `method='backward'` with `IBP=False`. Basically you need one extra parameter when creating BoundedModule:

```
bound_opts={"conv_mode": conv_mode}
```
You can take a look at the example here: https://github.com/KaidiXu/auto_LiRPA/blob/master/examples/vision/patch_convolution.py#L67

On the other hand, if your intention is training, you can also try to use a more efficient bounding method such as CROWN-IBP (IBP+backward), by setting 
```
featurenet.compute_bounds(IBP=True, method='backward') 
```
This yields looser bounds but should be sufficient for training.

**Comment by QuXinghuaNTU** [comment]
> "conv_mode": conv_mode

@huanzhang12 Thanks. Hope you guys are safe and healthy during this tough time in the US. Happy lunar new year ahead.
