### ISSUE TITLE
onnx::GlobalAveragePool

### ISSUE THREAD

**Issue by Kozon2015** [KaidiXu/auto_LiRPA#7]
hello! In the `bound_general.py`, you don't care abount `nodesOP[n].op == 'onnx::GlobalAveragePool'`

**Comment by huanzhang12** [comment]
@Kozon2015 Thanks for reporting this issue. We will try to add GlobalAveragePool in the next release.
If you have a specific network for your task, you can post it here so we can try to make sure it is working in the next release. Thanks!

**Comment by huanzhang12** [comment]
@Kozon2015 We have just made a new release with better pooling layer support. You can try the latest version of `auto_LiRPA` and see if the issue has been fixed or not. Thanks!
